### DISCUSSION TITLE
[Swagger] Append information about api possible versions

### DISCUSSION THREAD

**Discussion by westfin** [dotnet/aspnet-api-versioning#1006] [Q&A]
Hi guys, this question partially related to https://github.com/dotnet/aspnet-api-versioning/discussions/998

My X-Api-Version header parameter appeared in openapi document (snippet below). Does it possible to list possible version values for api? Currently we have only one active 1.0 version. But our clients want to see such info in document.

```yaml
parameters:
  - name: X-API-Version
    in: header
    description: The requested API version
    schema:
       type: string
```

Maybe if it is valid schema something like:

```yaml 
parameters:
  - name: X-API-Version
    in: header
    description: The requested API version
    schema:
       type: string
       enum: 
         - "1.0"
         - "2.0"
         - null
```
